from __future__ import annotations

from enum import Enum


class OperationCategory(str, Enum):
    MATERIAL_TRANSFORMATION = "MATERIAL_TRANSFORMATION"
    SURFACE_TREATMENT = "SURFACE_TREATMENT"
    JOINERY_PREPARATION = "JOINERY_PREPARATION"
    HARDWARE_PREPARATION = "HARDWARE_PREPARATION"
    HARDWARE_INSTALLATION = "HARDWARE_INSTALLATION"
    STRUCTURAL_ASSEMBLY = "STRUCTURAL_ASSEMBLY"
    MOVEMENT_ASSEMBLY = "MOVEMENT_ASSEMBLY"
    INSPECTION = "INSPECTION"
    IDENTIFICATION = "IDENTIFICATION"
    PACKAGING = "PACKAGING"


class OperationId(str, Enum):
    CUT_TO_SIZE = "CUT_TO_SIZE"
    TRIM_TO_SIZE = "TRIM_TO_SIZE"
    ROUT_GROOVE = "ROUT_GROOVE"
    CREATE_RABBET = "CREATE_RABBET"
    CREATE_POCKET = "CREATE_POCKET"
    SHAPE_PROFILE = "SHAPE_PROFILE"

    EDGE_BAND = "EDGE_BAND"
    SAND_SURFACE = "SAND_SURFACE"
    APPLY_FINISH = "APPLY_FINISH"
    LAMINATE_SURFACE = "LAMINATE_SURFACE"

    DRILL_CONFIRMAT_HOLES = "DRILL_CONFIRMAT_HOLES"
    DRILL_MINIFIX_HOLES = "DRILL_MINIFIX_HOLES"
    DRILL_SHELF_PIN_HOLES = "DRILL_SHELF_PIN_HOLES"
    DRILL_BACK_PANEL_FIXING_HOLES = "DRILL_BACK_PANEL_FIXING_HOLES"
    DRILL_ASSEMBLY_HOLES = "DRILL_ASSEMBLY_HOLES"

    DRILL_HINGE_CUP = "DRILL_HINGE_CUP"
    DRILL_HINGE_SCREW_HOLES = "DRILL_HINGE_SCREW_HOLES"
    DRILL_DRAWER_SLIDE_HOLES = "DRILL_DRAWER_SLIDE_HOLES"
    DRILL_HANDLE_HOLES = "DRILL_HANDLE_HOLES"
    DRILL_RAIL_SUPPORT_HOLES = "DRILL_RAIL_SUPPORT_HOLES"
    DRILL_LEG_FIXING_HOLES = "DRILL_LEG_FIXING_HOLES"

    INSTALL_HINGE = "INSTALL_HINGE"
    INSTALL_DRAWER_SLIDE = "INSTALL_DRAWER_SLIDE"
    INSTALL_HANDLE = "INSTALL_HANDLE"
    INSTALL_SHELF_PINS = "INSTALL_SHELF_PINS"
    INSTALL_WARDROBE_RAIL = "INSTALL_WARDROBE_RAIL"
    INSTALL_ADJUSTABLE_LEGS = "INSTALL_ADJUSTABLE_LEGS"
    INSTALL_MINIFIX = "INSTALL_MINIFIX"
    INSTALL_CONFIRMAT = "INSTALL_CONFIRMAT"

    ASSEMBLE_CARCASS = "ASSEMBLE_CARCASS"
    INSTALL_BACK_PANEL = "INSTALL_BACK_PANEL"
    INSTALL_SHELF = "INSTALL_SHELF"
    ASSEMBLE_DRAWER_BOX = "ASSEMBLE_DRAWER_BOX"
    INSTALL_DRAWER_FRONT = "INSTALL_DRAWER_FRONT"

    MOUNT_DOOR = "MOUNT_DOOR"
    INSERT_DRAWER = "INSERT_DRAWER"
    ALIGN_DOOR = "ALIGN_DOOR"
    ALIGN_DRAWER = "ALIGN_DRAWER"

    INSPECT_PANEL_DIMENSIONS = "INSPECT_PANEL_DIMENSIONS"
    INSPECT_HOLE_POSITIONS = "INSPECT_HOLE_POSITIONS"
    INSPECT_EDGE_COVERAGE = "INSPECT_EDGE_COVERAGE"
    INSPECT_DOOR_SWING_CLEARANCE = "INSPECT_DOOR_SWING_CLEARANCE"
    INSPECT_DRAWER_MOVEMENT = "INSPECT_DRAWER_MOVEMENT"
    INSPECT_BACK_PANEL_STABILITY = "INSPECT_BACK_PANEL_STABILITY"
    INSPECT_SHELF_SUPPORT = "INSPECT_SHELF_SUPPORT"
    INSPECT_HARDWARE_ALIGNMENT = "INSPECT_HARDWARE_ALIGNMENT"
    FINAL_ASSEMBLY_CHECK = "FINAL_ASSEMBLY_CHECK"

    LABEL_PART = "LABEL_PART"
    LABEL_CABINET = "LABEL_CABINET"
    GROUP_PARTS_BY_CABINET = "GROUP_PARTS_BY_CABINET"

    PACK_CABINET = "PACK_CABINET"
    PACK_HARDWARE_KIT = "PACK_HARDWARE_KIT"
    PREPARE_SHIPMENT = "PREPARE_SHIPMENT"


OPERATION_CATEGORY_BY_ID: dict[OperationId, OperationCategory] = {
    OperationId.CUT_TO_SIZE: OperationCategory.MATERIAL_TRANSFORMATION,
    OperationId.TRIM_TO_SIZE: OperationCategory.MATERIAL_TRANSFORMATION,
    OperationId.ROUT_GROOVE: OperationCategory.MATERIAL_TRANSFORMATION,
    OperationId.CREATE_RABBET: OperationCategory.MATERIAL_TRANSFORMATION,
    OperationId.CREATE_POCKET: OperationCategory.MATERIAL_TRANSFORMATION,
    OperationId.SHAPE_PROFILE: OperationCategory.MATERIAL_TRANSFORMATION,
    OperationId.EDGE_BAND: OperationCategory.SURFACE_TREATMENT,
    OperationId.SAND_SURFACE: OperationCategory.SURFACE_TREATMENT,
    OperationId.APPLY_FINISH: OperationCategory.SURFACE_TREATMENT,
    OperationId.LAMINATE_SURFACE: OperationCategory.SURFACE_TREATMENT,
    OperationId.DRILL_CONFIRMAT_HOLES: OperationCategory.JOINERY_PREPARATION,
    OperationId.DRILL_MINIFIX_HOLES: OperationCategory.JOINERY_PREPARATION,
    OperationId.DRILL_SHELF_PIN_HOLES: OperationCategory.JOINERY_PREPARATION,
    OperationId.DRILL_BACK_PANEL_FIXING_HOLES: OperationCategory.JOINERY_PREPARATION,
    OperationId.DRILL_ASSEMBLY_HOLES: OperationCategory.JOINERY_PREPARATION,
    OperationId.DRILL_HINGE_CUP: OperationCategory.HARDWARE_PREPARATION,
    OperationId.DRILL_HINGE_SCREW_HOLES: OperationCategory.HARDWARE_PREPARATION,
    OperationId.DRILL_DRAWER_SLIDE_HOLES: OperationCategory.HARDWARE_PREPARATION,
    OperationId.DRILL_HANDLE_HOLES: OperationCategory.HARDWARE_PREPARATION,
    OperationId.DRILL_RAIL_SUPPORT_HOLES: OperationCategory.HARDWARE_PREPARATION,
    OperationId.DRILL_LEG_FIXING_HOLES: OperationCategory.HARDWARE_PREPARATION,
    OperationId.INSTALL_HINGE: OperationCategory.HARDWARE_INSTALLATION,
    OperationId.INSTALL_DRAWER_SLIDE: OperationCategory.HARDWARE_INSTALLATION,
    OperationId.INSTALL_HANDLE: OperationCategory.HARDWARE_INSTALLATION,
    OperationId.INSTALL_SHELF_PINS: OperationCategory.HARDWARE_INSTALLATION,
    OperationId.INSTALL_WARDROBE_RAIL: OperationCategory.HARDWARE_INSTALLATION,
    OperationId.INSTALL_ADJUSTABLE_LEGS: OperationCategory.HARDWARE_INSTALLATION,
    OperationId.INSTALL_MINIFIX: OperationCategory.HARDWARE_INSTALLATION,
    OperationId.INSTALL_CONFIRMAT: OperationCategory.HARDWARE_INSTALLATION,
    OperationId.ASSEMBLE_CARCASS: OperationCategory.STRUCTURAL_ASSEMBLY,
    OperationId.INSTALL_BACK_PANEL: OperationCategory.STRUCTURAL_ASSEMBLY,
    OperationId.INSTALL_SHELF: OperationCategory.STRUCTURAL_ASSEMBLY,
    OperationId.ASSEMBLE_DRAWER_BOX: OperationCategory.STRUCTURAL_ASSEMBLY,
    OperationId.INSTALL_DRAWER_FRONT: OperationCategory.STRUCTURAL_ASSEMBLY,
    OperationId.MOUNT_DOOR: OperationCategory.MOVEMENT_ASSEMBLY,
    OperationId.INSERT_DRAWER: OperationCategory.MOVEMENT_ASSEMBLY,
    OperationId.ALIGN_DOOR: OperationCategory.MOVEMENT_ASSEMBLY,
    OperationId.ALIGN_DRAWER: OperationCategory.MOVEMENT_ASSEMBLY,
    OperationId.INSPECT_PANEL_DIMENSIONS: OperationCategory.INSPECTION,
    OperationId.INSPECT_HOLE_POSITIONS: OperationCategory.INSPECTION,
    OperationId.INSPECT_EDGE_COVERAGE: OperationCategory.INSPECTION,
    OperationId.INSPECT_DOOR_SWING_CLEARANCE: OperationCategory.INSPECTION,
    OperationId.INSPECT_DRAWER_MOVEMENT: OperationCategory.INSPECTION,
    OperationId.INSPECT_BACK_PANEL_STABILITY: OperationCategory.INSPECTION,
    OperationId.INSPECT_SHELF_SUPPORT: OperationCategory.INSPECTION,
    OperationId.INSPECT_HARDWARE_ALIGNMENT: OperationCategory.INSPECTION,
    OperationId.FINAL_ASSEMBLY_CHECK: OperationCategory.INSPECTION,
    OperationId.LABEL_PART: OperationCategory.IDENTIFICATION,
    OperationId.LABEL_CABINET: OperationCategory.IDENTIFICATION,
    OperationId.GROUP_PARTS_BY_CABINET: OperationCategory.IDENTIFICATION,
    OperationId.PACK_CABINET: OperationCategory.PACKAGING,
    OperationId.PACK_HARDWARE_KIT: OperationCategory.PACKAGING,
    OperationId.PREPARE_SHIPMENT: OperationCategory.PACKAGING,
}


CATEGORY_TO_OPERATION_IDS: dict[OperationCategory, tuple[OperationId, ...]] = {
    category: tuple(
        operation_id
        for operation_id, mapped_category in OPERATION_CATEGORY_BY_ID.items()
        if mapped_category == category
    )
    for category in OperationCategory
}


OPERATION_VOCABULARY_V1: tuple[OperationId, ...] = tuple(OPERATION_CATEGORY_BY_ID)

