from __future__ import annotations

from enum import Enum


class MountingType(str, Enum):
    CONCEALED_RAIL = "CONCEALED_RAIL"
    POINT_FIXED_BRACKET = "POINT_FIXED_BRACKET"
    FRENCH_CLEAT = "FRENCH_CLEAT"
    HYBRID_RETAINED = "HYBRID_RETAINED"


class WallType(str, Enum):
    CONCRETE = "CONCRETE"
    MASONRY = "MASONRY"
    TIMBER_STUD = "TIMBER_STUD"
    STEEL_STUD = "STEEL_STUD"
    PLASTERBOARD_OVER_STUD = "PLASTERBOARD_OVER_STUD"
    HOLLOW_BLOCK = "HOLLOW_BLOCK"


class AnchorType(str, Enum):
    EXPANSION_ANCHOR = "EXPANSION_ANCHOR"
    CHEMICAL_ANCHOR = "CHEMICAL_ANCHOR"
    STUD_SCREW = "STUD_SCREW"
    TOGGLE_BOLT = "TOGGLE_BOLT"
    CLEAT_HOOK = "CLEAT_HOOK"
    SAFETY_RETENTION = "SAFETY_RETENTION"


class SuspensionHardwareFamily(str, Enum):
    WALL_RAIL = "WALL_RAIL"
    ADJUSTABLE_HANGER = "ADJUSTABLE_HANGER"
    CONCEALED_BRACKET = "CONCEALED_BRACKET"
    CLEAT = "CLEAT"
    ANTI_LIFT_RETENTION = "ANTI_LIFT_RETENTION"


class LoadCategory(str, Enum):
    STATIC_DISTRIBUTED = "STATIC_DISTRIBUTED"
    CANTILEVER_MOMENT = "CANTILEVER_MOMENT"
    DOOR_OPEN_LOAD = "DOOR_OPEN_LOAD"
    SHELF_CONTENT_LOAD = "SHELF_CONTENT_LOAD"
    DYNAMIC_DISTURBANCE = "DYNAMIC_DISTURBANCE"


class ClearanceType(str, Enum):
    TOP_INSTALLATION = "TOP_INSTALLATION"
    SIDE_INSTALLATION = "SIDE_INSTALLATION"
    REAR_SERVICE = "REAR_SERVICE"
    LEVELING_ADJUSTMENT = "LEVELING_ADJUSTMENT"
    OPENING_PATH = "OPENING_PATH"


class FailureMode(str, Enum):
    ANCHOR_PULL_OUT = "ANCHOR_PULL_OUT"
    ANCHOR_SHEAR = "ANCHOR_SHEAR"
    BRACKET_DEFORMATION = "BRACKET_DEFORMATION"
    WALL_SUBSTRATE_CRACKING = "WALL_SUBSTRATE_CRACKING"
    CABINET_SAG_OR_TILT = "CABINET_SAG_OR_TILT"
    ANTI_LIFT_FAILURE = "ANTI_LIFT_FAILURE"
